# Generated by Django 4.2 on 2023-04-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_alter_user_birthday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_number',
            field=models.IntegerField(null=True),
        ),
    ]
