# Generated by Django 4.2 on 2023-04-19 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_personal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('Daily', 'مرخصی روزانه'), ('Hourly', 'مرخصی ساعتی')], max_length=50)),
                ('date', models.DateField()),
                ('from_hour', models.TimeField(null=True)),
                ('untill_hour', models.TimeField(null=True)),
                ('description', models.TextField()),
                ('is_accept', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vacation',
            },
        ),
    ]
