# Generated by Django 4.2 on 2023-04-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelTable(
            name='todolist',
            table='To Do List',
        ),
    ]
