# Generated by Django 4.2 on 2023-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_managermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='managermessage',
            name='image',
            field=models.ImageField(null=True, upload_to='manager message/images'),
        ),
        migrations.AddField(
            model_name='managermessage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managermessage',
            name='video',
            field=models.FileField(null=True, upload_to='manager message/video'),
        ),
        migrations.AlterField(
            model_name='managermessage',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
