# Generated by Django 4.2 on 2023-05-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_managermessage_image_managermessage_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('working_month', models.DateField()),
            ],
            options={
                'db_table': 'Working Month',
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_day', models.DateField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workingmonth')),
            ],
            options={
                'db_table': 'Working Day',
            },
        ),
    ]
