# Generated by Django 4.2 on 2023-05-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_workingmonth_workingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='dashboard.workingmonth'),
        ),
    ]
