# Generated by Django 4.2 on 2023-04-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Contract Type',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_Color', models.CharField(max_length=100)),
                ('receipt_number', models.IntegerField()),
                ('receipt_payment_date', models.DateField(null=True)),
                ('receipt_amount', models.IntegerField(null=True)),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contracttype')),
            ],
            options={
                'db_table': 'Receipt',
                'abstract': False,
            },
        ),
    ]
