# Generated by Django 4.2 on 2023-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('تسویه شده', 'تسویه شده'), ('تاخیر خورده', 'تاخیر خورده'), ('تمدید شده', 'تمدید شده')], max_length=50),
        ),
    ]
