# Generated by Django 4.2 on 2023-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.IntegerField(unique=True)),
                ('car_name', models.CharField(max_length=100, null=True)),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('car_Color', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('فروش', 'فروش'), ('حق العملکاری', 'حق العملکاری')], max_length=50)),
                ('receipt_number', models.IntegerField(unique=True)),
                ('receipt_payment_date', models.DateField(null=True)),
                ('receipt_amount', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Receipt',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('created_date',)},
        ),
        migrations.AddField(
            model_name='contract',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='car_Color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='car_delivery',
            field=models.CharField(choices=[('روزانه', 'روزانه'), ('ماهانه', 'ماهانه')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='car_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='day_of_delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='delay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='month_of_commission',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='month_of_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_of_car',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='car_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='national_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('تسویه شده', 'تسویه شده'), ('تاخیر خورده', 'تاخیر خورده'), ('تمدید شده', 'تمدید شده')], default='در حال انجام', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.ManyToManyField(related_name='receipts', to='contract.receipt'),
        ),
    ]
