# Generated by Django 4.2 on 2023-05-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_Color', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('contract_number', models.IntegerField(unique=True)),
                ('car_number', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('SALE', 'فروش'), ('COMMISSION', 'حق العملکاری')], max_length=50)),
                ('car_delivery', models.CharField(choices=[('DAILY', 'روزانه'), ('MONTHLY', 'ماهانه')], max_length=50, null=True)),
                ('day_of_delivery', models.IntegerField(null=True)),
                ('month_of_delivery', models.DateField(null=True)),
                ('month_of_commission', models.DateField(null=True)),
                ('status', models.CharField(choices=[('DOING', 'در حال انجام'), ('DONE', 'اتمام قرارداد'), ('DELAY', 'تاخیر قرارداد'), ('EXTENSION', 'تمدید قرارداد')], max_length=50)),
                ('image', models.ImageField(null=True, upload_to='contract/images')),
                ('receipt', models.ManyToManyField(related_name='receipt', to='contract.receipt')),
            ],
            options={
                'db_table': 'Contract',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='contract/images')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contract.contract')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
