# Generated by Django 4.2 on 2023-04-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DOING', 'در حال انجام'), ('DONE', 'اتمام قرارداد'), ('DELAY', 'تاخیر قرارداد'), ('EXTENSION', 'تمدید قرارداد')], max_length=50),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='contract/images')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contract.contract')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
