# Generated by Django 4.2 on 2023-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='car_delivery',
            field=models.CharField(choices=[('روزانه', 'روزانه'), ('ماهانه', 'ماهانه')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('فروش', 'فروش'), ('حق العملکاری', 'حق العملکاری')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('اتمام قرارداد', 'اتمام قرارداد'), ('تاخیر قرارداد', 'تاخیر قرارداد'), ('تمدید قرارداد', 'تمدید قرارداد')], max_length=50),
        ),
    ]
