# Generated by Django 4.2 on 2023-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_status_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(null=True, upload_to='contract/images'),
        ),
    ]
